// <auto-generated />
using System;
using FlightBoard.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightBoard.Infrastructure.Migrations
{
    [DbContext(typeof(FlightBoardContext))]
    [Migration("20250610231456_SeedFlightData")]
    partial class SeedFlightData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("FlightBoard.Core.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightNumber")
                        .IsUnique();

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 10, 23, 14, 56, 484, DateTimeKind.Utc).AddTicks(7075),
                            DepartureTime = new DateTime(2025, 6, 11, 1, 14, 56, 484, DateTimeKind.Utc).AddTicks(6324),
                            Destination = "London",
                            FlightNumber = "FL001",
                            Gate = "A1",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 10, 23, 14, 56, 484, DateTimeKind.Utc).AddTicks(7320),
                            DepartureTime = new DateTime(2025, 6, 11, 2, 14, 56, 484, DateTimeKind.Utc).AddTicks(7315),
                            Destination = "Paris",
                            FlightNumber = "FL002",
                            Gate = "B2",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 10, 23, 14, 56, 484, DateTimeKind.Utc).AddTicks(7333),
                            DepartureTime = new DateTime(2025, 6, 10, 23, 29, 56, 484, DateTimeKind.Utc).AddTicks(7321),
                            Destination = "New York",
                            FlightNumber = "FL003",
                            Gate = "C3",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 6, 10, 23, 14, 56, 484, DateTimeKind.Utc).AddTicks(7335),
                            DepartureTime = new DateTime(2025, 6, 11, 3, 14, 56, 484, DateTimeKind.Utc).AddTicks(7334),
                            Destination = "Tokyo",
                            FlightNumber = "FL004",
                            Gate = "D4",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
